---
title: "R Notebook"
output: html_notebook
---

```{r}
library(forecast)
```

```{r}
x1_ma<-arima.sim(n=200,list(ma=1)) 
plot(x1_ma)
x2_ma<-arima.sim(n=200,list(ma=-1))
plot(x2_ma)
```
```{r}
x1_ar<-arima.sim(n=200,list(ar=0.5))
plot(x1_ar)
x2_ar<-arima.sim(n=200,list(ar=-0.5))
plot(x2_ar)

```
```{r}
x1_arima<-arima.sim(n=200,list(order=c(2,0,1),ar=c(0.2,-0.1),ma=0.1))
plot(x1_arima)
x2_arima<-arima.sim(n=200,list(order=c(1,1,2),ar=0.3,ma=c(0.3,-0.4)))
plot(x2_arima) 
```
```{r}
auto.arima(x1_arima,max.p=2,max.q=2,stepwise=T,trace=T)
```
```{r}
x1_forecast<-Arima(x1_arima,order=c(2,0,1))
x2_forecast<-Arima(x2_arima,order=c(5,1,2))
plot(forecast(x1_forecast,level=c(50,95),h=150))
plot(forecast(x2_forecast,level=c(50,95),h=150))
```

```{r}
xt.arima1<-auto.arima(x1_arima,trace=T,stepwise=T,seasonal=T)
plot(forecast(xt.arima1,range=c(50,95),h=150))
xt.arima2<-auto.arima(x2_arima,trace=T,stepwise=T,seasonal=T)
plot(forecast(xt.arima2,range=c(50,95),h=150))
```
```{r}
y1<-rep(c(3,5,12,4),20)
y2<-20+20*sin(seq(from=-0.5*pi,to=0,length.out=80))
y<-y1+y2+rnorm(mean=0,sd=3,n=80)
yt<-ts(as.numeric(y),frequency=4)
plot(yt)
```
```{r}
yt.arima<-auto.arima(yt,trace=T,stepwise=T,seasonal=T)
plot(forecast(yt.arima,range=c(50,95),h=150))
```

```{r}
yt.arima<-auto.arima(yt,trace=T,stepwise=T,seasonal=F)
plot(forecast(yt.arima,range=c(50,95),h=150))
```
```{r}
yt.arima_noI<-Arima(yt,order=c(5,1,1))
plot(forecast(yt.arima_noI,range=c(50,95),h=150))
```

```{r}
tsdisplay(x1_arima)
tsdisplay(x2_arima)
```

